---

- name: Репозиторий Docker
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo
  tags:
    - install

- name: Установка docker-ce из репозитория
  package:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
    state: present
  tags:
    - install

- name: Служба docker
  service:
    name: docker
    state: started
    enabled: yes
  tags:
    - install

- name: docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.25.3/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    timeout: 60
  tags:
    - install

- name: Подготовка docker-compose к работе
  file:
    path: /usr/local/bin/docker-compose
    mode: +x
  tags:
    - install

- name: Docker SDK for Python
  pip:
    name: docker
    state: latest
    executable: pip3
  tags:
    - install